### ISSUE TITLE
Panic when declaring a variable of an unknown type

### ISSUE THREAD

**Issue by asahi3g** [skycoin/cx#134]
```
package main
func main()() {
    var i foo
}
```
Output:
```
panic: type 'foo' does not exist

goroutine 1 [running, locked to thread]:
github.com/skycoin/cx/cxgo/actions.DeclarationSpecifiersStruct(0xc4201e87e0, 0x3, 0x0, 0x0, 0xc4200c4d00, 0xc4201a3c01)
	/home/reash/go/src/github.com/skycoin/cx/cxgo/actions/declarations.go:359 +0x6d3
github.com/skycoin/cx/cxgo/cxgo0.yyParse(0x973800, 0xc42009b040, 0xc42009b040)
	/home/reash/go/src/github.com/skycoin/cx/cxgo/cxgo0/cxgo0.go:1910 +0x1ed7
github.com/skycoin/cx/cxgo/cxgo0.Parse(0xc4200902a0, 0x2e, 0x2d)
	/home/reash/go/src/github.com/skycoin/cx/cxgo/cxgo0/cxgo0.go:74 +0xc8
main.main()
	/home/reash/go/src/github.com/skycoin/cx/cxgo/cxgo.nn.go:8556 +0x367a
```

**Comment by ingwal** [comment]
This issue is solved somewhere before CX 0.6.2.  It's mentioned in the CHANGELOG for 0.6.2.
