### ISSUE TITLE
Panic when using a function declared in another package without importing the package

### ISSUE THREAD

**Issue by asahi3g** [skycoin/cx#156]
```
package issue
func foo() () {
}

package main
func main()() {
	issue.foo()
}
```
output:
```
panic: 

goroutine 1 [running, locked to thread]:
github.com/skycoin/cx/cxgo/actions.ProcessMethodCall(0xc4200a8e60, 0xc420059068, 0xc420059048, 0xc4201b2001)
	/home/reash/go/src/github.com/skycoin/cx/cxgo/actions/functions.go:608 +0xf00
github.com/skycoin/cx/cxgo/actions.FunctionDeclaration(0xc4201b2000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42009a160, 0x1, 0x1)
	/home/reash/go/src/github.com/skycoin/cx/cxgo/actions/functions.go:95 +0x2ed
main.yyParse(0x976a60, 0xc4203d4000, 0xc4203d4000)
	/home/reash/go/src/github.com/skycoin/cx/cxgo/cxgo.go:1718 +0x1d09
main.main()
	/home/reash/go/src/github.com/skycoin/cx/cxgo/cxgo.nn.go:8584 +0x1640
```

**Comment by ingwal** [comment]
This was fixed in CX 0.6.0 according to Amaury.  It's mentioned in the CX 0.6.2 CHANGELOG.
