### ISSUE TITLE
Panic when giving []f32 argument to gl.BufferData 

### ISSUE THREAD

**Issue by asahi3g** [skycoin/cx#24]
```
package main
import "glfw"
import "gl"

func foo(stride i32, attr []i32, verts []f32)(){
	printf("l0 %d, l1 %d", len(attr), len(verts))
	gl.BufferData(gl.ARRAY_BUFFER, 36 * 4, verts, gl.DYNAMIC_DRAW)
}

func main()() {
	var test str
	test = "test_24"
    printf("%s\n", test)

    glfw.Init()
    glfw.WindowHint(glfw.Resizable, glfw.False)
    glfw.CreateWindow(test, 800, 600, test)
    glfw.MakeContextCurrent(test)

    gl.Init()
	var attributes []i32
	attributes = []i32 {3 ,3}

	var vertices []f32
	vertices = []f32{
		 0.0,  1.0,  2.0,  3.0,  4.0,  5.0,
		 6.0,  7.0,  8.0,  9.0, 10.0, 11.0,
		12.0, 13.0, 14.0, 15.0, 16.0, 17.0,
		18.0, 19.0, 20.0, 21.0, 22.0, 23.0,
		24.0, 25.0, 26.0, 27.0, 28.0, 29.0,
		30.0, 31.0, 32.0, 33.0, 34.0, 35.0 }

	var vbo i32
	vbo = gl.GenBuffers(1, vbo)
	gl.BindBuffer(gl.ARRAY_BUFFER, vbo)

	foo(gl.TRIANGLES, attributes, vertices)
    printf("%s passed\n", test)
}
```
output:
```
test_24
panic: runtime error: slice bounds out of range

goroutine 1 [running, locked to thread]:
github.com/skycoin/cx/cx.op_len(0xc42008c960, 0x18)
	/home/reash/go/src/github.com/skycoin/cx/cx/op_und.go:283 +0x310
github.com/skycoin/cx/cx.execNative(0xc420073110)
	/home/reash/go/src/github.com/skycoin/cx/cx/opcodes.go:390 +0x2a8
github.com/skycoin/cx/cx.(*CXCall).ccall(0xc4201ea048, 0xc420073110, 0x0, 0x0)
	/home/reash/go/src/github.com/skycoin/cx/cx/execute.go:1576 +0x31f
github.com/skycoin/cx/cx.(*CXProgram).RunCompiled(0xc420073110, 0x0, 0x4, 0xc4201bd8c0)
	/home/reash/go/src/github.com/skycoin/cx/cx/execute.go:1500 +0x2ba
main.main()
	/home/reash/go/src/github.com/skycoin/cx/cxgo/cxgo.nn.go:8406 +0x1c68
```

**Comment by amherag** [comment]
It's now giving me this output without errors:

```
test_24
l0 2, l1 36test_24 passed
```

Is that the desired behavior? (other way to say that I'm too lazy/busy to understand the code and I want to start fixing another issue).

**Comment by asahi3g** [comment]
Yes, it looks like it's fixed.
