### ISSUE TITLE
Panic when trying to index (using a var) an array, member of a struct passed as a function argument...

### ISSUE THREAD

**Issue by asahi3g** [skycoin/cx#27]
```
package main

type too_s struct {
    ai [5]i32
}

func foo(too too_s) {
    var index i32 = 3
    too.ai[index] = 4
    assert(too.ai[index], 4, "")
}

func main()() {
    var too too_s
    foo(too)
}

```

output:

```
2018/09/05 22:36:50 Not enough buffer data to deserialize
panic: Not enough buffer data to deserialize

goroutine 1 [running, locked to thread]:
log.Panic(0xc4200af718, 0x1, 0x1)
	/usr/local/go/src/log/log.go:326 +0xc0
github.com/skycoin/skycoin/src/cipher/encoder.DeserializeAtomic(0xc4201ee018, 0x0, 0x927ac, 0x807d40, 0xc4200af780)
	/home/reash/go/src/github.com/skycoin/skycoin/src/cipher/encoder/encoder.go:136 +0x96
github.com/skycoin/cx/cx.ReadI32(0x18, 0xc420362dc0, 0x0)
	/home/reash/go/src/github.com/skycoin/cx/cx/op.go:299 +0xac
github.com/skycoin/cx/cx.GetFinalOffset(0x18, 0xc420362b40, 0x493e8)
	/home/reash/go/src/github.com/skycoin/cx/cx/op.go:47 +0xb9
github.com/skycoin/cx/cx.op_identity(0xc4203c4280, 0x18)
	/home/reash/go/src/github.com/skycoin/cx/cx/op_misc.go:52 +0x8d
github.com/skycoin/cx/cx.execNative(0xc420073110)
	/home/reash/go/src/github.com/skycoin/cx/cx/opcodes.go:357 +0xe9
github.com/skycoin/cx/cx.(*CXCall).ccall(0xc4201ec048, 0xc420073110, 0x0, 0x0)
	/home/reash/go/src/github.com/skycoin/cx/cx/execute.go:1589 +0x31f
github.com/skycoin/cx/cx.(*CXProgram).RunCompiled(0xc420073110, 0x0, 0x4, 0xc4201bde40)
	/home/reash/go/src/github.com/skycoin/cx/cx/execute.go:1513 +0x2ba
main.main()
	/home/reash/go/src/github.com/skycoin/cx/cxgo/cxgo.nn.go:8406 +0x1c68
```

It doesn't panic when using a literal to index the array.

**Comment by asahi3g** [comment]
When computing the finalOffset of the cx index var in cx/op.cx, line 8, func GetFinalOffset , the value of arg.TotalSize is 0.

When changing in file cx/config.go, line 265
from
```
"identifier": TYPE_IDENTIFIER,
```
to
```
"ident":TYPE_IDENTIFIER,
```

in order to match the "ident" string in TypeNames map, the arg.TotalSize is 4 and the sample does'n panic anymore. Now it asserts. Somehow the finalOffset is still not computed properly.

**Comment by amherag** [comment]
This got fixed now.
