### ISSUE TITLE
Crash when INIT_HEAP_SIZE limit is reached

### ISSUE THREAD

**Issue by asahi3g** [skycoin/cx#293]
**To Reproduce**
```
package main

func main()() {
	var s []i32
	var INIT_HEAP_SIZE i32 = 32 * (1 << 20) // TODO : should be tested against real cx/config.go::INIT_HEAP_SIZE
	for i := 0; i < INIT_HEAP_SIZE; i++ {
		s = append(s, 1)
	}
	test(len(s), INIT_HEAP_SIZE, "")
}
```
**Expected behavior**
Heap should grow until MAX_HEAP_SIZE is reached

**Screenshots**
```
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x9cf738, 0x16)
	/usr/local/go/src/runtime/panic.go:617 +0x72
runtime.sysMap(0xc004000000, 0x33334000000, 0xe145f8)
	/usr/local/go/src/runtime/mem_linux.go:170 +0xc7
runtime.(*mheap).sysAlloc(0xdfb440, 0x33330ac2000, 0xdfb450, 0x19998561)
	/usr/local/go/src/runtime/malloc.go:633 +0x1cd
runtime.(*mheap).grow(0xdfb440, 0x19998561, 0x0)
	/usr/local/go/src/runtime/mheap.go:1105 +0x42
runtime.(*mheap).allocSpanLocked(0xdfb440, 0x19998561, 0xe14608, 0x460db8)
	/usr/local/go/src/runtime/mheap.go:1033 +0x37f
runtime.(*mheap).alloc_m(0xdfb440, 0x19998561, 0x7f8dc47c0101, 0xdfb450)
	/usr/local/go/src/runtime/mheap.go:860 +0xc2
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:931 +0x4c
runtime.(*mheap).alloc(0xdfb440, 0x19998561, 0x7fff5d000101, 0x7f8dc47c56d8)
	/usr/local/go/src/runtime/mheap.go:930 +0x8a
runtime.largeAlloc(0x33330ac2000, 0x100, 0x7f8dc47c56d8)
	/usr/local/go/src/runtime/malloc.go:1055 +0x99
runtime.mallocgc.func1()
	/usr/local/go/src/runtime/malloc.go:950 +0x46
runtime.systemstack(0x499be9)
	/usr/local/go/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1153

goroutine 1 [running, locked to thread]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:311 fp=0xc000835258 sp=0xc000835250 pc=0x499ce0
runtime.mallocgc(0x33330ac2000, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/malloc.go:949 +0x871 fp=0xc0008352f8 sp=0xc000835258 pc=0x44fe61
runtime.growslice(0x8f2560, 0xc0001c8000, 0x300004, 0x300004, 0x33330ac0008, 0xc0008353e0, 0x7ea077, 0xc0002c8032)
	/usr/local/go/src/runtime/slice.go:175 +0x151 fp=0xc000835360 sp=0xc0008352f8 pc=0x485b01
github.com/skycoin/cx/cx.ResizeMemory(...)
	/home/reash/go/src/github.com/skycoin/cx/cx/op.go:247
github.com/skycoin/cx/cx.AllocateSeq(0x200011, 0x4)
	/home/reash/go/src/github.com/skycoin/cx/cx/op.go:271 +0x25d fp=0xc0008353f0 sp=0xc000835360 pc=0x77fd1d
github.com/skycoin/cx/cx.SliceResize(0x10002500100025, 0x40001, 0x4, 0x100018)
	/home/reash/go/src/github.com/skycoin/cx/cx/utilities.go:672 +0x361 fp=0xc0008354b0 sp=0xc0008353f0 pc=0x7ea4e1
github.com/skycoin/cx/cx.SliceAppend(0x10002500100025, 0xc0002c8018, 0x4, 0x1fffec, 0xc000835540)
	/home/reash/go/src/github.com/skycoin/cx/cx/utilities.go:701 +0x54 fp=0xc0008354f8 sp=0xc0008354b0 pc=0x7ea794
github.com/skycoin/cx/cx.opAppend(0xc000078e60, 0x0)
	/home/reash/go/src/github.com/skycoin/cx/cx/op_und.go:405 +0x219 fp=0xc000835590 sp=0xc0008354f8 pc=0x7ac619
github.com/skycoin/cx/cx.init.1.func1(0xc0004de000)
	/home/reash/go/src/github.com/skycoin/cx/cx/opcodes_bare.go:1476 +0x1664 fp=0xc0008355b8 sp=0xc000835590 pc=0x7eeb04
github.com/skycoin/cx/cx.init.3.func1(0xc0004de000)
	/home/reash/go/src/github.com/skycoin/cx/cx/opcodes_extra.go:780 +0x14c6 fp=0xc0008355f0 sp=0xc0008355b8 pc=0x7f0676
github.com/skycoin/cx/cx.(*CXCall).ccall(0xc0001c2000, 0xc0004de000, 0x0, 0x0)
	/home/reash/go/src/github.com/skycoin/cx/cx/execute.go:310 +0x331 fp=0xc0008356b0 sp=0xc0008355f0 pc=0x77e301
github.com/skycoin/cx/cx.(*CXProgram).Run(0xc0004de000, 0x9bed01, 0xc0008358c8, 0xffffffffffffffff, 0x0, 0x0)
	/home/reash/go/src/github.com/skycoin/cx/cx/execute.go:119 +0x117 fp=0xc0008357b8 sp=0xc0008356b0 pc=0x77ce47
github.com/skycoin/cx/cx.(*CXProgram).RunCompiled(0xc0004de000, 0x0, 0x0, 0x0, 0x0, 0xc0005040b0, 0x0)
	/home/reash/go/src/github.com/skycoin/cx/cx/execute.go:201 +0x238 fp=0xc0008358c0 sp=0xc0008357b8 pc=0x77d618
main.main()
	/home/reash/go/src/github.com/skycoin/cx/cxgo/cxgo.nn.go:8885 +0xce2 fp=0xc000835f98 sp=0xc0008358c0 pc=0x866f12
runtime.main()
	/usr/local/go/src/runtime/proc.go:200 +0x20c fp=0xc000835fe0 sp=0xc000835f98 pc=0x47150c
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000835fe8 sp=0xc000835fe0 pc=0x49bdb1
```

**Desktop:**
 - OS: Linux
 - CX Version : 0.6.1, https://github.com/skycoin/cx/commit/d8775bfb4500fde31a074507713fc0de47b64e11

**Comment by amherag** [comment]
This seems to be fixed now. For the record, I ran this code (which uses 2 Mb of heap memory as INIT_HEAP_SIZE; I also tried with 4 Mb and it worked, which means that CX is correctly expanding the heap size beyond INIT_HEAP_SIZE).

```
package main

func main()() {
	var s []i32
	var INIT_HEAP_SIZE i32 = 2097152
	for i := 0; i < INIT_HEAP_SIZE; i++ {
		s = append(s, 1)
	}
	test(len(s), INIT_HEAP_SIZE, "")
}
```
