### ISSUE TITLE
Panic when using arithmetic to index an array field of a struct.

### ISSUE THREAD

**Issue by asahi3g** [skycoin/cx#30]
```
package main

type too_s struct {
    ai [5]i32
}

func main()(){
    var too too_s
    too.ai[3 + 0] = 444
    assert(too.ai[3], 444, "")
}
```
output:
```
panic: runtime error: index out of range

goroutine 1 [running, locked to thread]:
github.com/skycoin/cx/cxgo/actions.PostfixExpressionArray(0xc420314030, 0x1, 0x1, 0xc420314068, 0x1, 0x1, 0x9, 0xc420314068, 0x1)
	/home/reash/go/src/github.com/skycoin/cx/cxgo/actions/cxgo_compiled.go:675 +0xca1
main.yyParse(0x9486e0, 0xc42030e000, 0xc42030e000)
	/home/reash/go/src/github.com/skycoin/cx/cxgo/cxgo.go:2042 +0x60a1
main.main()
	/home/reash/go/src/github.com/skycoin/cx/cxgo/cxgo.nn.go:8369 +0x1470
```

**Comment by amherag** [comment]
Fixed.
