### ISSUE TITLE
Panic if return value is used in an expression

### ISSUE THREAD

**Issue by asahi3g** [skycoin/cx#32]
```
package main

func foob()(ret bool) {
    ret = true
}

func fooi()(ret i32) {
    ret = 5
}

func main()() {
    var b bool = foob() == true
    var i i32 = fooi() + 5
    if fooi() < 6 {}
    if foob() == true {}
}
```
output:
```
panic: runtime error: index out of range

goroutine 1 [running, locked to thread]:
github.com/skycoin/cx/cxgo/actions.ArithmeticOperation(0xc4203c6078, 0x1, 0x1, 0xc4203c6088, 0x1, 0x1, 0xc4201244d0, 0xc4200af3a0, 0xbaa6e658, 0xf813e7b5bf0ba804)
	/home/reash/go/src/github.com/skycoin/cx/cxgo/actions/cxgo_compiled.go:1036 +0x10de
github.com/skycoin/cx/cxgo/actions.ShorthandExpression(0xc4203c6078, 0x1, 0x1, 0xc4203c6088, 0x1, 0x1, 0x0, 0x1, 0x1, 0x1)
	/home/reash/go/src/github.com/skycoin/cx/cxgo/actions/cxgo_compiled.go:934 +0xa3
main.yyParse(0x9486e0, 0xc4203c0000, 0xc4203c0000)
	/home/reash/go/src/github.com/skycoin/cx/cxgo/cxgo.go:2136 +0x768d
main.main()
	/home/reash/go/src/github.com/skycoin/cx/cxgo/cxgo.nn.go:8369 +0x1470

```

**Comment by Lunier** [comment]
You need to use braces after an if statement, so it should look like this:

func main()() {
    var b bool = foob() == true
    var i i32 = fooi() + 5
    if (fooi() < 6) {}
    if (foob() == true) {}
}
