### ISSUE TITLE
Update Examples: examples/opengl/game.cx needs to be updated

### ISSUE THREAD

**Issue by MarcoRezkallah** [skycoin/cx#347]
when running cx examples/opengl/game.cx 
I got the following output.
```
panic: struct 'CreateShader' not found in package 'gl'

goroutine 1 [running, locked to thread]:
github.com/skycoin/cx/cxgo/actions.PostfixExpressionField(0xc00009e188, 0x1, 0x1, 0xc0007e4910, 0xc, 0xc0000204f8, 0x0, 0x1)
	/home/amherag/go/src/github.com/skycoin/cx/cxgo/actions/postfix.go:311 +0x189c
github.com/skycoin/cx/cxgo/parser.yyParse(0xd74320, 0xc0000ca000, 0xc0000ca000)
	/home/amherag/go/src/github.com/skycoin/cx/cxgo/parser/cxgo.go:2096 +0x6635
github.com/skycoin/cx/cxgo/parser.Parse(0xc0000ca000, 0xc000184070)
	/home/amherag/go/src/github.com/skycoin/cx/cxgo/parser/cxgo.go:18 +0x37
main.main()
	/home/amherag/go/src/github.com/skycoin/cx/cxgo/main.go:836 +0xf91

```

OS: ubuntu 20.04

**Comment by archerixx** [comment]
Same happens on Windows, 'CreateShader' is missing

**Comment by SkycoinSynth** [comment]
Example Needs to be updated
