### ISSUE TITLE
Panic when accessing property of struct array passed in as argument to func

### ISSUE THREAD

**Issue by redcurse** [skycoin/cx#35]
```
package main

type Structure struct {
    integer i32
}

func function(structure []Structure) {
    var test i32
    test = structure[0].integer // <--- cant access property of array
}

func main() {
    var structures []Structure
    var structure Structure

    structure.integer = 123

    structures = append(structures, structure)
    function(structures)
}
```
output
```
panic: runtime error: integer divide by zero

goroutine 1 [running, locked to thread]:
github.com/skycoin/cx/cxgo/actions.PreFinalSize(0xc00007f038, 0xc000318b40, 0xc000197180)
        C:/Users/Jay/go/src/github.com/skycoin/cx/cxgo/actions/cxgo_compiled.go:1442 +0x1c0
github.com/skycoin/cx/cxgo/actions.SetFinalSize(0xc00007f1f0, 0xc000318b40)
        C:/Users/Jay/go/src/github.com/skycoin/cx/cxgo/actions/cxgo_compiled.go:1478 +0x115
github.com/skycoin/cx/cxgo/actions.ProcessExpressionArguments(0xc00007f1f0, 0xc00007f1e8, 0xc00007f1d0, 0xc000191290, 0xc000006050, 0x1, 0x1, 0xc00036a140, 0x1)
        C:/Users/Jay/go/src/github.com/skycoin/cx/cxgo/actions/cxgo_compiled.go:1956 +0x1e0
github.com/skycoin/cx/cxgo/actions.FunctionDeclaration(0xc000191290, 0xc000006028, 0x1, 0x1, 0x0, 0x0, 0x0, 0xc000040080, 0x2, 0x2)
        C:/Users/Jay/go/src/github.com/skycoin/cx/cxgo/actions/cxgo_compiled.go:1985 +0x2f5
main.yyParse(0xa46220, 0xc000312000, 0xc000312000)
        C:/Users/Jay/go/src/github.com/skycoin/cx/cxgo/cxgo.go:1714 +0x1b2a
main.main()
        C:/Users/Jay/go/src/github.com/skycoin/cx/cxgo/cxgo.nn.go:8369 +0x6d2
```

**Comment by redcurse** [comment]
I think I found a workaround for now.
```
package main

type Structure struct {
    integer i32
}

func function(structure []Structure) {
    var test Structure
    test = structure[0]
    i32.print(test.integer) // <--- This works!
}

func main() {
    var structures []Structure
    var structure Structure

    structure.integer = 123

    structures = append(structures, structure)
    function(structures)
}
```

**Comment by amherag** [comment]
Fixed!
