### ISSUE TITLE
List of non-working CX examples

### ISSUE THREAD

**Issue by 0pcom** [skycoin/cx#377]
**Describe the bug**

Nonworking CX examples

**To Reproduce**
1. Go to cx examples dir
2. run each example with `cx` <example_name>.cx

**Expected behavior**

Example should complete without errors

**Desktop (please complete the following information):**
 - OS: Arch Linux x86_64

**Additional context**

Non-working CX examples:

examples/

```
$cx bubble-sort.cx
error: bubble-sort.cx:38 function 'i32.add' expected receiving variable of type 'i32'; 'ident' was provided
error: bubble-sort.cx:38 wrong index type; expected either 'i32' or 'i64', got 'ident'


$ cx digital-root.cx
        Digital Root Example
I will set the value for you :)
The value is 30
And I will call digiatlRoot() with base 10
error: digital-root.cx:14, CX_RUNTIME_SLICE_INDEX_OUT_OF_RANGE, 9
===Callstack===
>>> digiatlRoot()
Inputs
	digital-root.cx:12 : digiatlRoot() : 30
Inputs
	digital-root.cx:12 : digiatlRoot() : 10
Outputs
	digital-root.cx:12 : digiatlRoot() : []
Expressions
 	digital-root.cx:16 : i32.add() : 0
	digital-root.cx:20 : i32.gteq() : false

>>> main()
Expressions
 	digital-root.cx:38 : i32.gt() : true
	digital-root.cx:30 : digiatlRoot() : []

goroutine 1 [running, locked to thread]:
runtime/debug.Stack(0xc000069740, 0xc35400, 0xc000069690)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/skycoin/cx/cx.runtimeErrorInfo(0xc346c0, 0xe7e078, 0xe7e001, 0x5)
	/home/amherag/go/src/github.com/skycoin/cx/cx/utilities.go:835 +0x21d
github.com/skycoin/cx/cx.RuntimeError()
	/home/amherag/go/src/github.com/skycoin/cx/cx/utilities.go:858 +0x171
panic(0xc346c0, 0xe7e078)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/skycoin/cx/cx.CalculateDereferences(0xc00024e900, 0xc0000e11e0, 0x5, 0x0)
	/home/amherag/go/src/github.com/skycoin/cx/cx/op.go:52 +0x94d
github.com/skycoin/cx/cx.GetFinalOffset(0x5, 0xc00024e900, 0x5)
	/home/amherag/go/src/github.com/skycoin/cx/cx/op.go:151 +0x6c
github.com/skycoin/cx/cx.opIdentity(0xc0002543c0, 0x5)
	/home/amherag/go/src/github.com/skycoin/cx/cx/op_misc.go:34 +0x89
github.com/skycoin/cx/cx.init.2.func1(0xc0001c01c0)
	/home/amherag/go/src/github.com/skycoin/cx/cx/opcodes_core.go:937 +0x121
github.com/skycoin/cx/cx.init.3.func1(0xc0001c01c0)
	/home/amherag/go/src/github.com/skycoin/cx/cx/opcodes_extra.go:594 +0xf33
github.com/skycoin/cx/cx.(*CXCall).ccall(0xc00030e018, 0xc0001c01c0, 0x0, 0x0)
	/home/amherag/go/src/github.com/skycoin/cx/cx/execute.go:278 +0x35d
github.com/skycoin/cx/cx.(*CXProgram).Run(0xc0001c01c0, 0xd7f101, 0xc0000e1550, 0xffffffffffffffff, 0x0, 0x0)
	/home/amherag/go/src/github.com/skycoin/cx/cx/execute.go:118 +0x120
github.com/skycoin/cx/cx.(*CXProgram).RunCompiled(0xc0001c01c0, 0x0, 0x0, 0x0, 0x0, 0xc00009c820, 0x0)
	/home/amherag/go/src/github.com/skycoin/cx/cx/execute.go:200 +0x21d
main.main()
	/home/amherag/go/src/github.com/skycoin/cx/cxgo/main.go:813 +0x10cf


$ cx errors.cx
error: errors.cx:7, CX_RUNTIME_ERROR, runtime error: integer divide by zero
===Callstack===
>>> main()
Expressions
 	errors.cx:4 : identity() : 10
	errors.cx:5 : identity() : 5.5
	errors.cx:7 : i32.div() : 0

goroutine 1 [running, locked to thread]:
runtime/debug.Stack(0xa, 0xc0000e50c0, 0x3)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/skycoin/cx/cx.runtimeErrorInfo(0xcbf2c0, 0x15e1c80, 0x15e1c01, 0x5)
	/home/amherag/go/src/github.com/skycoin/cx/cx/utilities.go:835 +0x21d
github.com/skycoin/cx/cx.RuntimeError()
	/home/amherag/go/src/github.com/skycoin/cx/cx/utilities.go:858 +0x171
panic(0xcbf2c0, 0x15e1c80)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/skycoin/cx/cx.opI32Div(0xc0000b32c0, 0x0)
	/home/amherag/go/src/github.com/skycoin/cx/cx/op_i32.go:67 +0x124
github.com/skycoin/cx/cx.init.2.func1(0xc000624000)
	/home/amherag/go/src/github.com/skycoin/cx/cx/opcodes_core.go:1042 +0x836



$ cx temp-converter.cx
error: temp-converter.cx:15 operands are not of the same type
```

examples/book/

```
$ cx affordances-expression.cx
error: affordances-expression.cx:16 cannot assign value of type '[]aff' to identifier 'tgt' of type 'aff'
error: affordances-expression.cx:20 cannot assign value of type '[]aff' to identifier 'fltrs' of type 'aff'

$ cx affordances-filter.cx
error: affordances-filter.cx:13 cannot assign value of type '[]aff' to identifier 'fltrs' of type 'aff'

$ cx cxbase-program.cx
cxbase-program.cx:25: syntax error: unexpected IDENTIFIER

$ cx cxbase-sum.cx
cxbase-sum.cx:3: syntax error: unexpected LPAREN

$ cx datatypes-slices-native.cx
error: datatypes-slices-native.cx:8 function 'make' not found in package 'main'
error: datatypes-slices-native.cx:11 function 'make' not found in package 'main'

$ cx datatypes-slices-native.cx
error: datatypes-slices-native.cx:8 function 'make' not found in package 'main'
error: datatypes-slices-native.cx:11 function 'make' not found in package 'main'

$ cx deserialization-program.cx
error: deserialization-program.cx:8 function 'serialize' expected input argument of type 'aff'; '[]aff' was provided
error: deserialization-program.cx:8 function 'serialize' expected receiving variable of type 'byte'; '[]byte' was provided
error: deserialization-program.cx:9 function 'deserialize' expected input argument of type 'byte'; '[]byte' was provided

$ cx functions-lexical-scoping.cx
error: functions-lexical-scoping.cx:4 identifier 'x' does not exist
error: functions-lexical-scoping.cx:4 function 'i32.print' expected input argument of type 'i32'; 'ident' was provided

$ cx genetic-programming-example.cx
genetic-programming-example.cx:25: syntax error: unexpected IDENTIFIER


$ cx intro-typespecific.cx
error: intro-typespecific.cx:6 function 'print' not found in package 'main'

$ cx pointers-example-1.cx
error: pointers-example-1.cx:15 function 'makeCells' not found in package 'main'
error: pointers-example-1.cx:16 identifier 'glfw' does not exist

$ cx repr-function-redefinition.cx
error: repr-function-redefinition.cx:5 function redeclaration

$ cx serialization-declarations.cx
serialization-declarations.cx:19: syntax error: unexpected VAR

$ cx serialization-expression.cx
serialization-expression.cx:21: syntax error: unexpected VAR


$ cx serialization-memory.cx
serialization-memory.cx:7: syntax error: unexpected RBRACE

$ cx serialization-package.cx
serialization-package.cx:7: syntax error: unexpected RBRACE


$ cx serialization-program.cx
error: serialization-program.cx:8 function 'serialize' expected input argument of type 'aff'; '[]aff' was provided
error: serialization-program.cx:8 function 'serialize' expected receiving variable of type 'byte'; '[]byte' was provided

$ cx unittest-example.cx
error: unittest-example.cx:9 operator 'assert' expects to return 1 output, but 0 receiving arguments were provided
```

examples/data-structures/

```
$ cx structs.cx
error: structs.cx:21 'p' redeclared
```

examples/opengl

```
$ cx bouncing-ball-control.cx
panic: runtime error: index out of range

goroutine 1 [running, locked to thread]:
github.com/skycoin/cx/cxgo/actions.ShorthandExpression(0xc00000e6d8, 0x1, 0x1, 0xc00000e718, 0x1, 0x1, 0x9, 0x1, 0x1, 0xc0000b04c0)
	/home/amherag/go/src/github.com/skycoin/cx/cxgo/actions/expressions.go:288 +0x4f6
github.com/skycoin/cx/cxgo/parser.yyParse(0xe88ac0, 0xc0000d8550, 0xc0000d8550)
	/home/amherag/go/src/github.com/skycoin/cx/cxgo/parser/cxgo.go:2140 +0x6eaf
github.com/skycoin/cx/cxgo/parser.Parse(0xc0000d8550, 0xc0001da000)
	/home/amherag/go/src/github.com/skycoin/cx/cxgo/parser/cxgo.go:18 +0x37
main.main()
	/home/amherag/go/src/github.com/skycoin/cx/cxgo/main.go:779 +0xf07

$ cx conways-game-of-life.cx
error: conways-game-of-life.cx:225 function 'gl.BufferData' expected input argument of type '[]f32'; '[18]f32' was provided
error: conways-game-of-life.cx:227 'vao' redeclared

$ cx conways-game-of-life-gc.cx
error: conways-game-of-life-gc.cx:223 function 'gl.BufferData' expected input argument of type '[]f32'; '[18]f32' was provided
error: conways-game-of-life-gc.cx:225 'vao' redeclared

$ cx draw-elements.cx
error: draw-elements.cx:192 field '*lcl_30' not found in struct 'Block'
error: draw-elements.cx:192 field '*lcl_30' not found in struct 'Block'
error: draw-elements.cx:191 function 'f32.sub' expected input argument of type 'f32'; '' was provided

$ cx smooth-motion-control.cx
error: smooth-motion-control.cx:201 operands are not of the same type
```

examples/serialization/

```
$ cx example.cx
error: example.cx:2 
```

examples/affordances/

ALL AFFORDANCE EXAMPLES FAIL WITH FOLLOWING ERRORS:
```
error: argument-expression.cx:17 cannot assign value of type '[]aff' to identifier 'tgt' of type 'aff'
error: argument-expression.cx:21 cannot assign value of type '[]aff' to identifier 'fltrs' of type 'aff'
```

**Comment by 0pcom** [comment]
The examples for converting between types which appear here:
https://cx.skycoin.net/docs

are all throwing an `index out of range` error
Here is one of them
```
$ cat convert.cx
package main

func main () {
	var num str
	num = "33"

	byte.print(5B + str.byte(num))
	i32.print(33 + str.f32(num))
	i64.print(10L + str.i64(num))
	f32.print(50.111 + str.f32(num))
	f64.print(50.111D + str.f32(num))
}
```

When I run it:
```
$ cx convert.cx
panic: runtime error: index out of range

goroutine 1 [running, locked to thread]:
github.com/skycoin/cx/cxgo/actions.ShorthandExpression(0xc00000e108, 0x1, 0x1, 0xc00000e130, 0x1, 0x1, 0x9, 0x1, 0x1, 0x1)
	/home/amherag/go/src/github.com/skycoin/cx/cxgo/actions/expressions.go:288 +0x4f6
github.com/skycoin/cx/cxgo/parser.yyParse(0xe88ac0, 0xc0000d8000, 0xc0000d8000)
	/home/amherag/go/src/github.com/skycoin/cx/cxgo/parser/cxgo.go:2140 +0x6eaf
github.com/skycoin/cx/cxgo/parser.Parse(0xc0000d8000, 0xc0001da000)
	/home/amherag/go/src/github.com/skycoin/cx/cxgo/parser/cxgo.go:18 +0x37
main.main()
	/home/amherag/go/src/github.com/skycoin/cx/cxgo/main.go:779 +0xf07

```

**Comment by 0pcom** [comment]
testing the blockchain examples; only one failure

initialized with:
```
cx --blockchain --secret-key $SECRET_KEY --public-key $PUBLIC_KEY examples/blockchain/genetic-bc.cx
```
and the other steps per the cx chains tutorial

```
$  cx --secret-key $SECRET_KEY --broadcast /examples/blockchain/genetic-txn.cx
==== Iteration 1, Accuracy 6/10 ====
==== Iteration 2, Accuracy 6/10 ====
==== Iteration 3, Accuracy 6/10 ====
==== Iteration 4, Accuracy 6/10 ====
==== Iteration 5, Accuracy 6/10 ====
==== Iteration 6, Accuracy 6/10 ====
==== Iteration 7, Accuracy 6/10 ====
==== Iteration 8, Accuracy 6/10 ====
==== Iteration 9, Accuracy 6/10 ====
==== Iteration 10, Accuracy 6/10 ====
panic: Post http://127.0.0.1:6421/api/v1/wallet/transaction: EOF

goroutine 1 [running, locked to thread]:
main.main()
	/home/user/go/src/github.com/skycoin/cx/cxgo/main.go:957 +0x5d6e
```

Interestingly, this is the same error as appears in #395 though it doesn't seem related to read()
