### ISSUE TITLE
CX Chains: cx --publisher wrong paths and race condition

### ISSUE THREAD

**Issue by 0pcom** [skycoin/cx#380]
**Desktop:**
 - OS: Arch Linux 4.19.43-1-lts x86_64
 - CX Version: 0.7beta

**Describe the bug**

This is in reference to the procedure outlined in the [CX Chains Tutorial](
https://github.com/skycoin/cx/wiki/CX-Chains-Tutorial#setup-process)

The errors occur at the `cx --publisher` step

**Expected behavior**

Command completes without error

**To Reproduce**

```
$ export SECRET_KEY=1414535274594b23ca0090cdc01e6b7b31702525583eb01c8650a650d4a8c99d
$ export PUBLIC_KEY=02583e5ebbf85522474e0f17e681e62ca37910db6b8792763af4e97663c31a7984
$ cx --blockchain --heap-initial 100 --stack-size 100 --secret-key $SECRET_KEY --public-key $PUBLIC_KEY counter-bc.cx
[2019-05-23T12:23:59-05:00] INFO [newcoin]: deleting /home/user/.cxcoin/data.db
[2019-05-23T12:24:00-05:00] INFO [newcoin]: Scanner: [2019-05-23T12:24:00-05:00] INFO [main]: App version: 0.25.0-rc1
[2019-05-23T12:24:00-05:00] INFO [newcoin]: Scanner: [2019-05-23T12:24:00-05:00] INFO [main]: Opening database /home/user/.cxcoin/data.db
[2019-05-23T12:24:00-05:00] INFO [newcoin]: Scanner: [2019-05-23T12:24:00-05:00] INFO [main]: DB version not found in DB
[2019-05-23T12:24:00-05:00] INFO [newcoin]: Scanner: [2019-05-23T12:24:00-05:00] INFO [main]: DB verify checkpoint version: 0.25.0
[2019-05-23T12:24:00-05:00] INFO [newcoin]: Scanner: [2019-05-23T12:24:00-05:00] INFO [main]: Checking database
[2019-05-23T12:24:00-05:00] INFO [newcoin]: Scanner: [2019-05-23T12:24:00-05:00] INFO [main]: Coinhour burn factor for user transactions is 2
[2019-05-23T12:24:00-05:00] INFO [newcoin]: Scanner: [2019-05-23T12:24:00-05:00] INFO [main]: Max transaction size for user transactions is 32768
[2019-05-23T12:24:00-05:00] INFO [newcoin]: Scanner: [2019-05-23T12:24:00-05:00] INFO [main]: Max decimals for user transactions is 3
[2019-05-23T12:24:00-05:00] INFO [newcoin]: Scanner: [2019-05-23T12:24:00-05:00] INFO [daemon]: Incoming connections are disabled.
[2019-05-23T12:24:00-05:00] INFO [newcoin]: Scanner: [2019-05-23T12:24:00-05:00] INFO [visor]: Creating new visor
[2019-05-23T12:24:00-05:00] INFO [newcoin]: Scanner: [2019-05-23T12:24:00-05:00] INFO [visor]: Visor running in block publisher mode
[2019-05-23T12:24:00-05:00] INFO [newcoin]: Scanner: [2019-05-23T12:24:00-05:00] INFO [visor]: Coinhour burn factor for unconfirmed transactions is 2
[2019-05-23T12:24:00-05:00] INFO [newcoin]: Scanner: [2019-05-23T12:24:00-05:00] INFO [visor]: Max transaction size for unconfirmed transactions is 32768
[2019-05-23T12:24:00-05:00] INFO [newcoin]: Scanner: [2019-05-23T12:24:00-05:00] INFO [visor]: Max decimals for unconfirmed transactions is 3
[2019-05-23T12:24:00-05:00] INFO [newcoin]: Scanner: [2019-05-23T12:24:00-05:00] INFO [visor]: Coinhour burn factor for transactions when creating blocks is 2
[2019-05-23T12:24:00-05:00] INFO [newcoin]: Scanner: [2019-05-23T12:24:00-05:00] INFO [visor]: Max transaction size for transactions when creating blocks is 32768
[2019-05-23T12:24:00-05:00] INFO [newcoin]: Scanner: [2019-05-23T12:24:00-05:00] INFO [visor]: Max decimals for transactions when creating blocks is 3
[2019-05-23T12:24:00-05:00] INFO [newcoin]: Scanner: [2019-05-23T12:24:00-05:00] INFO [visor]: Max block size is 32768
[2019-05-23T12:24:00-05:00] INFO [newcoin]: Scanner: [2019-05-23T12:24:00-05:00] INFO [blockdb]: Unspents.MaybeBuildIndexes
[2019-05-23T12:24:00-05:00] INFO [newcoin]: Scanner: [2019-05-23T12:24:00-05:00] INFO [blockdb]: Rebuilding unspent_pool_addr_index (addrHeightIndexExists=false, addrIndexHeight=0, headSeq=0)
[2019-05-23T12:24:00-05:00] INFO [newcoin]: Scanner: [2019-05-23T12:24:00-05:00] INFO [blockdb]: Building unspent address index
[2019-05-23T12:24:00-05:00] INFO [newcoin]: Scanner: [2019-05-23T12:24:00-05:00] INFO [blockdb]: No unspents to index
[2019-05-23T12:24:00-05:00] INFO [newcoin]: Scanner: [2019-05-23T12:24:00-05:00] INFO [visor]: Visor initHistory
[2019-05-23T12:24:00-05:00] INFO [newcoin]: Scanner: [2019-05-23T12:24:00-05:00] INFO [visor]: Resetting historyDB
[2019-05-23T12:24:00-05:00] INFO [newcoin]: Scanner: [2019-05-23T12:24:00-05:00] INFO [visor]: Visor parseHistoryTo
[2019-05-23T12:24:00-05:00] INFO [newcoin]: Scanner: [2019-05-23T12:24:00-05:00] INFO [visor]: Unconfirmed transaction pool size: 0
[2019-05-23T12:24:00-05:00] INFO [newcoin]: Scanner: [2019-05-23T12:24:00-05:00] WARN [api]: HTTPS not in use!
[2019-05-23T12:24:00-05:00] INFO [newcoin]: Scanner: [2019-05-23T12:24:00-05:00] INFO [pex]: Trying to download peers list url="https://127.0.0.1/peers.txt"
[2019-05-23T12:24:00-05:00] INFO [newcoin]: Scanner: [2019-05-23T12:24:00-05:00] INFO [main:CRITICAL]: Full address: http://127.0.0.1:6420
[2019-05-23T12:24:00-05:00] INFO [newcoin]: Scanner: [2019-05-23T12:24:00-05:00] INFO [visor]: Visor init
[2019-05-23T12:24:00-05:00] INFO [newcoin]: Scanner: [2019-05-23T12:24:00-05:00] INFO [visor]: Visor maybeCreateGenesisBlock
[2019-05-23T12:24:00-05:00] INFO [newcoin]: Scanner: [2019-05-23T12:24:00-05:00] INFO [visor]: Create genesis block
[2019-05-23T12:24:00-05:00] INFO [newcoin]: Scanner: [2019-05-23T12:24:00-05:00] ERROR [pex]: waiting to retry downloadText error="Get https://127.0.0.1/peers.txt: dial tcp 127.0.0.1:443: connect: connection refused" waitTime=699.774423ms
[2019-05-23T12:24:00-05:00] INFO [newcoin]: Scanner: [2019-05-23T12:24:00-05:00] INFO [visor]: Genesis block signature=842b0e54642bc61d53035ae70a2bd99a7db69935ea66a38ba47f8fbf16c35fee5c41fbb3a8fb331298d10ffc158b529ae0f3c42fe8c5d314fa20d2fff8f469d401
[2019-05-23T12:24:00-05:00] INFO [newcoin]: genesis sig: 842b0e54642bc61d53035ae70a2bd99a7db69935ea66a38ba47f8fbf16c35fee5c41fbb3a8fb331298d10ffc158b529ae0f3c42fe8c5d314fa20d2fff8f469d401
[2019-05-23T12:24:00-05:00] INFO [newcoin]: opening visor db: /home/user/.cxcoin/data.db
[2019-05-23T12:24:00-05:00] INFO [visor]: Creating new visor
[2019-05-23T12:24:00-05:00] INFO [visor]: Coinhour burn factor for unconfirmed transactions is 2
[2019-05-23T12:24:00-05:00] INFO [visor]: Max transaction size for unconfirmed transactions is 32768
[2019-05-23T12:24:00-05:00] INFO [visor]: Max decimals for unconfirmed transactions is 3
[2019-05-23T12:24:00-05:00] INFO [visor]: Coinhour burn factor for transactions when creating blocks is 2
[2019-05-23T12:24:00-05:00] INFO [visor]: Max transaction size for transactions when creating blocks is 32768
[2019-05-23T12:24:00-05:00] INFO [visor]: Max decimals for transactions when creating blocks is 3
[2019-05-23T12:24:00-05:00] INFO [visor]: Max block size is 32768
[2019-05-23T12:24:00-05:00] INFO [blockdb]: Unspents.MaybeBuildIndexes
[2019-05-23T12:24:00-05:00] INFO [visor]: Visor initHistory
[2019-05-23T12:24:00-05:00] INFO [visor]: Unconfirmed transaction pool size: 0

genesis signature: 842b0e54642bc61d53035ae70a2bd99a7db69935ea66a38ba47f8fbf16c35fee5c41fbb3a8fb331298d10ffc158b529ae0f3c42fe8c5d314fa20d2fff8f469d401
```
The above step completed successfully
Below is the error:

```
$ export GENESIS_ADDRESS=23v7mT1uLpViNKZHh9aww4VChxizqKsNq4E
$ export GENESIS_SIGNATURE=842b0e54642bc61d53035ae70a2bd99a7db69935ea66a38ba47f8fbf16c35fee5c41fbb3a8fb331298d10ffc158b529ae0f3c42fe8c5d314fa20d2fff8f469d401
$ cx --publisher --genesis-address $GENESIS_ADDRESS --genesis-signature $GENESIS_SIGNATURE --secret-key $SECRET_KEY --public-key $PUBLIC_KEY
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4de6de]

goroutine 8 [running]:
os.(*Process).signal(0x0, 0xe8a480, 0x1601ff0, 0x0, 0x0)
	/usr/local/go/src/os/exec_unix.go:56 +0x2e
os.(*Process).Signal(0x0, 0xe8a480, 0x1601ff0, 0xdc8440, 0xc0000566c8)
	/usr/local/go/src/os/exec.go:131 +0x3f
os.(*Process).kill(0x0, 0xc0005e8000, 0xc0000566c8)
	/usr/local/go/src/os/exec_posix.go:54 +0x43
os.(*Process).Kill(0x0, 0x0, 0x0)
	/usr/local/go/src/os/exec.go:116 +0x2b
main.main.func1(0xc000101080, 0xe89840, 0xc00000f218)
	/home/amherag/go/src/github.com/skycoin/cx/cxgo/main.go:339 +0x222
created by main.main
	/home/amherag/go/src/github.com/skycoin/cx/cxgo/main.go:330 +0x1d0
```

**Additional context**

The source of this behavior is apparently that goroutine 8  is looking in `/usr/local/go/` which does not exist on this system; instead of searching in GOROOT.

For Arch linux; GOROOT is in: /usr/lib/go

It may be possible to work around this for the moment.

Might I suggest, as a long-term solution, release binaries be created after installing `go` in the aforementioned standard location?

I have created [a debian package of the latest version of golang](https://github.com/0pcom/skydebs/releases/download/skydebs/go-1.12.4-1.deb) from the archlinux golang package which I have tested and can confirm works on debian, as a means to this end.

Here are debian packages for [skywire](https://github.com/0pcom/skydebs/releases/download/skydebs/skywire-20190505-1.deb) and [skywire-mainnet](https://github.com/0pcom/skydebs/releases/download/skydebs/skywire-mainnet-20190509-1.deb) for additional reference as to the install location.

**Comment by 0pcom** [comment]
I was not able to get it working either by symlinking or copying the files to that path, or by pointing GOROOT to /usr/local/go.

**Comment by 0pcom** [comment]
2dbug was able to help me get `make install` working on archlinux but when I try to run `cx --publisher` the error looks familiar
```
$ cx --publisher --genesis-address $GENESIS_ADDRESS --genesis-signature $GENESIS_SIGNATURE --secret-key $SECRET_KEY --public-key $PUBLIC_KEY
CX 0.7beta
More information about CX is available at http://cx.skycoin.net/ and https://github.com/skycoin/cx/
:func main {...
	* panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x50acde]

goroutine 23 [running]:
os.(*Process).signal(0x0, 0xf553c0, 0x1530130, 0x0, 0x0)
	/usr/lib/go/src/os/exec_unix.go:56 +0x2e
os.(*Process).Signal(...)
	/usr/lib/go/src/os/exec.go:131
os.(*Process).kill(...)
	/usr/lib/go/src/os/exec_posix.go:55
os.(*Process).Kill(0x0, 0x0, 0x0)
	/usr/lib/go/src/os/exec.go:116 +0x45
main.main.func1(0xc000103340, 0xf54a00, 0xc0000bb228)
	/home/user/go/src/github.com/skycoin/cx/cxgo/main.go:339 +0x218
created by main.main
	/home/user/go/src/github.com/skycoin/cx/cxgo/main.go:330 +0x201

**Comment by 0pcom** [comment]
If cx is installed in the system directories; cx expects to be run from `/`

The following error is produced when cx is called from within it's installed directory `/usr/lib/skycoin/go/src/github.com/skycoin/cx`

```
user@host cx]$ cx --blockchain --heap-initial 100 --stack-size 100 --secret-key $SECRET_KEY --public-key $PUBLIC_KEY examples/blockchain/counter-bc.cx
panic: stat usr/lib/skycoin/go/src/github.com/skycoin/cx/fiber.toml: no such file or directory

goroutine 1 [running, locked to thread]:
main.main()
	/home/user/.cache/yay/cx/src/go/src/github.com/skycoin/cx/cxgo/main.go:873 +0x5b01
```
In the first part of the error; fiber.toml does indeed exist along that path, however, the lack of a `/` before the path keeps it from being found except when cx is run from `/`

The second part of the error is a reference to the directory cx was built in. The files along that path are deleted once the package has been created and are not considered part of the installation; as they are put into the package and copied to the installed location in the system when the package is installed.

The result of the second error is a non-distributable (and not completely functional) package. CX (as well as all other skyware) should be able to be packaged in a distributable form. It may be installed on many machines within the same network and need only be built once in order to be distributed.

**Comment by 0pcom** [comment]
From what I can gather; one part of this error is due to some kind of race condition.
Reference [these](https://github.com/golang/go/issues/19326) [other](https://github.com/golang/go/issues/21135) [issues](https://github.com/golang/go/issues/22757)

The paths issue may be resolved by allowing for a default GOPATH as outlined [here](https://github.com/canthefason/go-watcher/pull/25) in case the GOPATH is empty (which is optional since go 1.8)

**Comment by 0pcom** [comment]
cx --publisher looks for cxcoin, the error messages were unhelpful. was able to make it work by symlinking cxcoin to /usr/bin/cxcoin
