### ISSUE TITLE
cx chains read() error

### ISSUE THREAD

**Issue by 0pcom** [skycoin/cx#395]
**Desktop (please complete the following information):**
 - OS: ArchLinux 4.19.46-1-lts x86_64
 - CX Version 0.7beta+

**Describe the bug**
read() causes errors in cx chains

**To Reproduce**

initialize the following cx chains application (per the cx chains tutorial) to test read()

```
$ cat message-txn.cx
package main
import "bc"

func main() {
	bc.incChatter()
}

$ cat message-bc.cx
package bc

var msg str
func incChatter() {
  msg = read()
}

package main
func main () {
}
```

broadcast a transaction:

```
$ cx --secret-key $SECRET_KEY --broadcast message-txn.cx

panic: Post http://127.0.0.1:6421/api/v1/wallet/transaction: EOF

goroutine 1 [running, locked to thread]:
main.main()
	/home/user/go/src/github.com/skycoin/cx/cxgo/main.go:952 +0x5ca7
```

The peer node starts giving errors at this point and must be restarted

**Expected behavior**
transaction completes without error

**Comment by ingwal** [comment]
The file I/O package is terrible in CX, including Read().  We will improve it ASAP.
That said, I am not sure that this is the reason for the crash.

**Comment by 0pcom** [comment]
I was testing the read() example above with cx 0.7.1 when I noticed that the blockchain counter example;
```
examples/blockchain/counter-bc.cx
examples/blockchain/counter-txn.cx
```
is now failing to print the counted number in the terminal, as was the previously observed behavior.

The transaction does appear to register in the peer node; and if I use a recent version of cx to preform just that transaction (without changing the publisher or peer) the incremented number does print, however the wallet was not set so it gives an error.

The recent version of cx in the following commands is `cx-7e` while `cx` is version 0.7.1
I also repeated this test with the provided (v0.7.1) binary `cx-071` to make certain the error was not introduced by the make process on my system.
```
$ cx-7e --secret-key $SECRET_KEY --broadcast examples/blockchain/counter-txn.cx
Blockchain counter: 4
400 Bad Request - missing wallet_id
$ cx --secret-key $SECRET_KEY --broadcast examples/blockchain/counter-txn.cx
$ cx-7e --secret-key $SECRET_KEY --broadcast examples/blockchain/counter-txn.cx
Blockchain counter: 5
400 Bad Request - missing wallet_id
$ cx-7e --secret-key $SECRET_KEY --broadcast examples/blockchain/counter-txn.cx
Blockchain counter: 5
400 Bad Request - missing wallet_id
$ cx --secret-key $SECRET_KEY --broadcast examples/blockchain/counter-txn.cx
$ cx --secret-key $SECRET_KEY --broadcast examples/blockchain/counter-txn.cx
400 Bad Request - Please spend after your pending transaction is confirmed
$ cx --secret-key $SECRET_KEY --broadcast examples/blockchain/counter-txn.cx
$ cx --secret-key $SECRET_KEY --broadcast examples/blockchain/counter-txn.cx
$ cx-7e --secret-key $SECRET_KEY --broadcast examples/blockchain/counter-txn.cx
Blockchain counter: 8
400 Bad Request - missing wallet_id
$ cx-071 --secret-key $SECRET_KEY --broadcast examples/blockchain/counter-txn.cx
$ cx-7e --secret-key $SECRET_KEY --broadcast examples/blockchain/counter-txn.cx
Blockchain counter: 9
400 Bad Request - missing wallet_id
```

The original error with read() still also exists in cx 0.7.1

**Comment by 0pcom** [comment]
Here is a little more info from further tests. I thought perhaps I should call read() from the transaction code instead of the blockchain code, however the same thing happened.

Here's a bit more detailed of an example:
hello1 = "sometext"
```
$ cat read-txn.cx
package main

import "bc"

var hello1 str
var local str

func main() {
//for bool.not(str.eq(hello1, "q")) {
str.print(sprintf("Type your message or q to quit:\n"))
hello1 = read()
if str.eq(hello1, "prev") {
local = bc.cxPrev()
str.print(local)
} else {
bc.cxChat(hello1)
}
}
}

$ cat read-bc.cx
package bc
var prevmessage str
var empty str
var out str

func cxChat (in str) (){
//print the previous message if it is not empty or don't try to print it if it's not empty
if bool.not(str.eq(prevmessage, empty)) {
str.print(sprintf("Previous message: \n%s", prevmessage))
}
//print the current message
str.print(sprintf("Current message: \n%s", in))
//set prevmessage as equal to the input from last time
prevmessage = in
//sanity check
str.print(prevmessage)
}

func cxPrev () (out str) {
out = prevmessage
}

package main
// the whole main package is discarded if run in --blockchain mode
func main() {
}
```
When I try to run it, all the output I would expect to be in the terminal where I ran the transaction is now appearing in the output of the peer node; the third line being an error with read():

```
INFO [newcoin]: Scanner: [2019-07-28T14:18:53-05:00] INFO [api]: 200 GET /api/v1/csrf 148.268µs
 INFO [newcoin]: Scanner: Type your message or q to quit:
 INFO [newcoin]: Scanner: 
 INFO [newcoin]: Scanner: error: :0, CX_RUNTIME_ERROR, 
 INFO [newcoin]: Scanner: ===Callstack===
 INFO [newcoin]: Scanner: >>> main()
 INFO [newcoin]: Scanner: Expressions
 INFO [newcoin]: Scanner:  	:0 : str.eq() : 
 INFO [newcoin]: Scanner: 	:0 : str.eq() : false
 INFO [newcoin]: Scanner: 	:0 : bool.not() : true
 INFO [newcoin]: Scanner: 	:0 : sprintf() : Type your message or q to quit:
 INFO [newcoin]: Scanner: 
 INFO [newcoin]: Scanner: 	:0 : str.eq() : false
 INFO [newcoin]: Scanner: 	:0 : cxPrev() : 
 INFO [newcoin]: Scanner: 
 ERROR [newcoin]: goroutine 285 [running]:
 ERROR [newcoin]: runtime/debug.Stack(0x1d, 0x0, 0x0)
 ERROR [newcoin]: 	/usr/lib/go/src/runtime/debug/stack.go:24 +0x9d
 ERROR [newcoin]: runtime/debug.PrintStack()
 ERROR [newcoin]: 	/usr/lib/go/src/runtime/debug/stack.go:16 +0x22
 ERROR [newcoin]: github.com/skycoin/cx/cx.runtimeErrorInfo(0xb254c0, 0xd5b6d0, 0xd5b601, 0x5)
 ERROR [newcoin]: 	/home/user/go/src/github.com/skycoin/cx/cx/utilities.go:898 +0x2c1
 ERROR [newcoin]: github.com/skycoin/cx/cx.RuntimeError()
 ERROR [newcoin]: 	/home/user/go/src/github.com/skycoin/cx/cx/utilities.go:921 +0x16d
 ERROR [newcoin]: panic(0xb254c0, 0xd5b6d0)
 ERROR [newcoin]: 	/usr/lib/go/src/runtime/panic.go:522 +0x1b5
 ERROR [newcoin]: github.com/skycoin/cx/cx.opRead(0xc000186000)
 ERROR [newcoin]: 	/home/user/go/src/github.com/skycoin/cx/cx/op_und.go:671 +0x4d8
 ERROR [newcoin]: github.com/skycoin/cx/cx.execNative(0xc000186000)
 ERROR [newcoin]: 	/home/user/go/src/github.com/skycoin/cx/cx/opcodes_core.go:300 +0x11b
 ERROR [newcoin]: github.com/skycoin/cx/cx.(*CXCall).ccall(0xc000154000, 0xc000186000, 0x0, 0x0)
 ERROR [newcoin]: 	/home/user/go/src/github.com/skycoin/cx/cx/execute.go:317 +0x32a
 ERROR [newcoin]: github.com/skycoin/cx/cx.(*CXProgram).Run(0xc000186000, 0xc1e201, 0xc000262b08, 0xffffffffffffffff, 0x0, 0x0)
 ERROR [newcoin]: 	/home/user/go/src/github.com/skycoin/cx/cx/execute.go:118 +0x126
 ERROR [newcoin]: github.com/skycoin/cx/cx.(*CXProgram).RunCompiled(0xc000186000, 0x0, 0x0, 0x0, 0x0, 0x11c7, 0xc000670000)
```

When I change the transaction code from `hello=read()` to `hello1 = "sometext"` it stores the string variable on the blockchain successfully, but still nothing is printed in the terminal where the transaction was run; only in the peer node output:

```
INFO [newcoin]: Scanner: [2019-07-28T14:32:01-05:00]  INFO [api]: 200 GET /api/v1/csrf 123.832µs
INFO [newcoin]: Scanner: Type your message or q to quit:
INFO [newcoin]: Scanner: 
INFO [newcoin]: Scanner: Current message: 
INFO [newcoin]: Scanner: sometext
INFO [newcoin]: Scanner: sometext
INFO [newcoin]: Scanner: INFO [api]: 200 POST /api/v1/wallet/transaction 11.152186ms
INFO [newcoin]: Scanner: INFO [api]: 200 POST /api/v1/injectTransaction 4.44363ms
INFO [newcoin]: Scanner: [2019-07-28T14:32:03-05:00] INFO [daemon:CRITICAL]: Added new block seq=2
```
