### ISSUE TITLE
defining & initializing slices/arrays on 1 line doesn't work with struct, PANICS

### ISSUE THREAD

**Issue by corpusc** [skycoin/cx#437]
...and gives  no file/line info.
This is with a single field, my next Issue report shows a different kind of error when you have 3 fields.  At least you get some file/line info in THAT case (but not THIS Issue's case).

**To Reproduce**
1. Use code:

package main

type Color3 struct {
	R f32
}

func main() {
	var nums [3]i32 = [3]i32{ 1, 2, 3 }
	var colors [1]Color3 = [1]Color3{Color3{R: 1.0}}
}

2. If you comment out the "var colors" line, you see it works fine with i32s

**Screenshots**
panic: runtime error: index out of range

goroutine 1 [running, locked to thread]:
github.com/skycoin/cx/cxgo/actions.CheckTypes(0xc000059b80)
        C:/Users/Amaury/go/src/github.com/skycoin/cx/cxgo/actions/functions.go:620 +0x10b6
github.com/skycoin/cx/cxgo/actions.FunctionDeclaration(0xc00005c680, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0000542a0, 0x8, 0xc)
        C:/Users/Amaury/go/src/github.com/skycoin/cx/cxgo/actions/functions.go:166 +0x48f
github.com/skycoin/cx/cxgo/parser.yyParse(0x100cd60, 0xc000092000, 0xc000092000)
        C:/Users/Amaury/go/src/github.com/skycoin/cx/cxgo/parser/cxgo.go:1744 +0x1d40
github.com/skycoin/cx/cxgo/parser.Parse(0xc000092000, 0xc00018c000)
        C:/Users/Amaury/go/src/github.com/skycoin/cx/cxgo/parser/cxgo.go:18 +0x3e
main.main()
        C:/Users/Amaury/go/src/github.com/skycoin/cx/cxgo/main.go:826 +0xf52

**Desktop:**
 - OS: Windows 10
 - CX Version 0.7.0 full release

**Comment by corpusc** [comment]
ACTUALLY, EVEN THE 
"var nums [3]i32 = [3]i32{ 1, 2, 3 }"
line causes the same kind of PANIC if you you don't set some initial values
( var nums [3]i32 = [3]i32{} )

**Comment by ingwal** [comment]
Note that these 2 lines:
  var nums [3]i32 = [3]i32{ 1, 2, 3 }
  var colors [1]Color3 = [1]Color3{Color3{R: 1.0}}
lack a comma at the end of the initializers.  They should be:
  var nums [3]i32 = [3]i32{ 1, 2, 3, }
  var colors [1]Color3 = [1]Color3{Color3{R: 1.0},}
The error message is still bad, though, so we will keep the error report.
