### ISSUE TITLE
def'ing & init'ing slices/arrays on 1 line CLAIMS STRUCT DOESN'T EXIST (with MULTIFIELD structs)

### ISSUE THREAD

**Issue by corpusc** [skycoin/cx#438]
**Describe the bug**
It still panics like Issue 437, but gives some file/line info before panicking.

**To Reproduce**

1. 

package main

type Color3 struct {
	R f32
	G f32
	B f32
}

func main() {
	var nums []i32 = []i32{ 1, 2, 3 }
	var colors []Color3 = []Color3{ Color3{ R: 1.0, G: 1.0, B: 1.0 } }
}

**Expected behavior**
For it to not lie about struct, and for it to work.

**Screenshots**

error: c.cx:11 identifier 'Color3' does not exist
error: c.cx:11 field 'R' in struct literal of type 'Color3' expected argument of type 'Color3'; 'f32' was provided
error: c.cx:11 cannot assign value of type 'f32' to identifier 'R' of type ''
error: c.cx:11 identifier 'Color3' does not exist
error: c.cx:11 field 'G' in struct literal of type 'Color3' expected argument of type 'Color3'; 'f32' was provided
error: c.cx:11 cannot assign value of type 'f32' to identifier 'G' of type ''
panic: runtime error: index out of range

goroutine 1 [running, locked to thread]:
github.com/skycoin/cx/cxgo/actions.CheckTypes(0xc000063cc0)
        C:/Users/Amaury/go/src/github.com/skycoin/cx/cxgo/actions/functions.go:620 +0x10b6
github.com/skycoin/cx/cxgo/actions.FunctionDeclaration(0xc00006e5b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc00009c240, 0xa, 0xc)
        C:/Users/Amaury/go/src/github.com/skycoin/cx/cxgo/actions/functions.go:166 +0x48f
github.com/skycoin/cx/cxgo/parser.yyParse(0x100cd60, 0xc0000aa000, 0xc0000aa000)
        C:/Users/Amaury/go/src/github.com/skycoin/cx/cxgo/parser/cxgo.go:1744 +0x1d40
github.com/skycoin/cx/cxgo/parser.Parse(0xc0000aa000, 0xc0001a8000)
        C:/Users/Amaury/go/src/github.com/skycoin/cx/cxgo/parser/cxgo.go:18 +0x3e
main.main()
        C:/Users/Amaury/go/src/github.com/skycoin/cx/cxgo/main.go:826 +0xf52

**Desktop (please complete the following information):**
 - OS: Windows 10
 - CX Version 0.7.0 full release

**Comment by ingwal** [comment]
Notice that the initializers are lacking a comma:
  var nums []i32 = []i32{ 1, 2, 3 }
should be
  var nums []i32 = []i32{ 1, 2, 3, }

But the error message is still garbage.
