### ISSUE TITLE
Serialize/Deserialize issue

### ISSUE THREAD

**Issue by archerixx** [skycoin/cx#462]
Running [`deserialization-program.cx`](https://github.com/skycoin/cx/blob/develop/examples/book/deserialization-program.cx) from cx/examples/book produces error:
```
error: deserialization-program.cx:5 struct 'byte' not found in package 'main'
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x38 pc=0x7ff64f0fc59c]

goroutine 1 [running, locked to thread]:
github.com/skycoin/cx/cxgo/actions.DeclarationSpecifiers(0x0, 0xc0001db1e0, 0x1, 0x1, 0x3, 0xc0000221c0)
        C:/Users/tursi/OneDrive/Desktop/go-workspace/src/github.com/skycoin/CX/cxgo/actions/declarations.go:412 +0x2bc
github.com/skycoin/cx/cxgo/cxgo0.yyParse(0x7ff64f434900, 0xc00015c6c0, 0xc00015c6c0)
        C:/Users/tursi/OneDrive/Desktop/go-workspace/src/github.com/skycoin/CX/cxgo/cxgo0/cxgo0.go:1796 +0x2985
github.com/skycoin/cx/cxgo/cxgo0.Parse(0xc0001963c0, 0x96, 0x95)
        C:/Users/tursi/OneDrive/Desktop/go-workspace/src/github.com/skycoin/CX/cxgo/cxgo0/cxgo0.go:27 +0xce
github.com/skycoin/cx/cxgo/cxgo.lexerStep0(0xc0001f8de0, 0x1, 0x1, 0xc0001f8dd0, 0x1, 0x1, 0x0)
        C:/Users/tursi/OneDrive/Desktop/go-workspace/src/github.com/skycoin/CX/cxgo/cxgo/cxgo.go:346 +0x24fb
github.com/skycoin/cx/cxgo/cxgo.ParseSourceCode(0xc000224490, 0x1, 0x1, 0xc0001f8dd0, 0x1, 0x1)
        C:/Users/tursi/OneDrive/Desktop/go-workspace/src/github.com/skycoin/CX/cxgo/cxgo/cxgo.go:39 +0xab0
main.parseProgram(0x0, 0x7ff64f425f70, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        C:/Users/tursi/OneDrive/Desktop/go-workspace/src/github.com/skycoin/CX/cmd/cx/m
```

**Comment by archerixx** [comment]
After changing `byte` with `i8` different issue comes up:
```
error: deserialization-program.cx:8 function 'serialize' expected input argument of type 'aff'; '[]aff' was provided
error: deserialization-program.cx:8 function 'serialize' expected receiving variable of type 'ui8'; '[]i8' was provided
error: deserialization-program.cx:9 function 'deserialize' expected input argument of type 'ui8'; '[]i8' was provided
```

**Comment by archerixx** [comment]
Duplicate. Issue exists under https://github.com/skycoin/cx/issues/56

**Comment by SkycoinSynth** [comment]
Duplicate of #56
