### ISSUE TITLE
Does cxLang parser exception handling or picnic have an elegant way to throw or return errors?

### ISSUE THREAD

**Issue by Liberxue** [skycoin/cx#529]
# Input
```

/* ----------------------------------------------
This example explains, how we can use different packages in our main package and 
how the Global variables and structures can be used in the main package from the other imported packages. 
*/


//Package for adding 
//
package foo1

// Defining global structure in the foo1 package 
//Point is the name of the structure 
//
type Point struct {

// x , y are the variables with file type i32
	x i32
	y i32
}

// This function is an example of adding variables
//
func double (n i32) (res i32) {
	res = i32.add(n, n)
}

// Package for multiplication 
//
package foo2

// This function allow a variable to multiply with 3
//
func triple (n i32) (res i32) {
	res = i32.mul(n, 3)
}





// Main package 
//
package main

// This is how to import various packages in the main package
import "foo1"
import "foo2"

// main() is the starting function in the program. 
//
func main () {

// Point is the structure from foo1 package
// we are defining a variable p of type Point
//This is how we can define a variable from another package, by considering it as a type. 
//
	var p Point

// we are assigning the values to the p variable
// Tis is how we can assign the values to a variable of type structure from an other package
// In foo1.Point{} foo1 is package and Point is the structure, by writing foo1.Point{} we can access Point from the foo1 and assign the values to x and y
	p = foo1.Point{x: 10,y: 20}

// p.x will allow to access the value in x
// p.y will allow to access the values in y
//simple print the i32 file type in the terminal
//
	i32.print(p.x)
	i32.print(p.y)
	
  // Defining variables         
	var double_return i32
	var triple_return i32
	
// 	here we are using a function double() from package foo1 and triple() from package foo2
//
	double_return = foo1.double(10)
	triple_return = foo2.triple(10)

// simple print the i32 file type in the terminal
	i32.print(double_return)
	i32.print(triple_return)
}


```

# Out

```
Starting web service for CX playground on http://127.0.0.1:5336/
panic: struct 'Point' not found in package 'foo1' [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x13d97b6]

goroutine 21 [running]:
github.com/skycoin/cx/cxgo/parser.(*Lexer).stop(...)
        /Users/liberxue/Coding/golang/src/github.com/skycoin/cx/cxgo/parser/scanner.go:50
github.com/skycoin/cx/cxgo/parser.(*Lexer).Stop(...)
        /Users/liberxue/Coding/golang/src/github.com/skycoin/cx/cxgo/parser/lexer.go:31
github.com/skycoin/cx/cmd/cxplayground/playground.unsafeeval.func1(0xc0000b9f90, 0xc0000b9f00)
        /Users/liberxue/Coding/golang/src/github.com/skycoin/cx/cmd/cxplayground/playground/playground.go:135 +0xb6
panic(0x14193a0, 0xc0000ec110)
        /usr/local/Cellar/go/1.15.6/libexec/src/runtime/panic.go:969 +0x1b9
github.com/skycoin/cx/cxgo/actions.DeclareStruct(0xc000098270, 0x5, 0xc0000ec0d0, 0x2, 0x2)
        /Users/liberxue/Coding/golang/src/github.com/skycoin/cx/cxgo/actions/declarations.go:189 +0x325
github.com/skycoin/cx/cxgo/cxgo0.yyParse(0x15088c0, 0xc0000a8240, 0xc0000a8240)
        /Users/liberxue/Coding/golang/src/github.com/skycoin/cx/cxgo/cxgo0/cxgo0.go:1652 +0x871
github.com/skycoin/cx/cxgo/cxgo0.Parse(0xc0001c8000, 0x7b6, 0x300000)
        /Users/liberxue/Coding/golang/src/github.com/skycoin/cx/cxgo/cxgo0/cxgo0.go:27 +0xca
github.com/skycoin/cx/cmd/cxplayground/playground.unsafeeval(0xc0001c8000, 0x7b6, 0xc000028210, 0x2a)
        /Users/liberxue/Coding/golang/src/github.com/skycoin/cx/cmd/cxplayground/playground/playground.go:149 +0x285
github.com/skycoin/cx/cmd/cxplayground/playground.eval.func1(0xc0001c8000, 0x7b6, 0xc0000ec0a0, 0xc000090000)
        /Users/liberxue/Coding/golang/src/github.com/skycoin/cx/cmd/cxplayground/playground/playground.go:186 +0x35
created by github.com/skycoin/cx/cmd/cxplayground/playground.eval
        /Users/liberxue/Coding/golang/src/github.com/skycoin/cx/cmd/cxplayground/playground/playground.go:185 +0xd5
```

# Expect

Does ``cxLang`` parser exception handling or picnic have an elegant way to throw or return errors?

**Comment by Liberxue** [comment]
Uploading BugEmersion.mov…

**Comment by Liberxue** [comment]
https://user-images.githubusercontent.com/5831248/111262892-f24bc880-865f-11eb-9ffc-c215ba3de1d9.mov
