### ISSUE TITLE
benchmark scripts

### ISSUE THREAD

**Issue by Diablo2050** [skycoin/cx#536]
The following work after adding import "time" 
- factorial-iterative.cx
- factorial-recursive.cx

The following aren't working after import "time":
- digital-root.cx
generates the following:

```The value is 79563
error: digital-root.cx:14, CX_RUNTIME_SLICE_INDEX_OUT_OF_RANGE, 9
===Callstack===
>>> digiatlRoot()
Inputs
        digital-root.cx:13 : digiatlRoot() : 79563
Inputs
        digital-root.cx:13 : digiatlRoot() : 10
Outputs
        digital-root.cx:13 : digiatlRoot() : []
Expressions
        digital-root.cx:17 : i32.add() : 0
        digital-root.cx:21 : i32.gteq() : false

>>> main()
Expressions
        digital-root.cx:25 : time.UnixNano() : 1616155064493003109
        digital-root.cx:0 : i32.gt() : true
        digital-root.cx:29 : digiatlRoot() : []
        digital-root.cx:39 : time.UnixNano() : 0
        digital-root.cx:41 : i64.sub() : 0

goroutine 1 [running, locked to thread]:
runtime/debug.Stack(0xc000200590, 0x98a600, 0xc000200320)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9f
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x25
github.com/skycoin/cx/cx.runtimeErrorInfo(0x989ac0, 0xab7c90, 0xab7c01, 0x5)
        /home/amr/Documents/misc/golang/cx/cx/utilities.go:936 +0x2d6
github.com/skycoin/cx/cx.RuntimeError()
        /home/amr/Documents/misc/golang/cx/cx/utilities.go:959 +0x172
panic(0x989ac0, 0xab7c90)
        /usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/skycoin/cx/cx.CalculateDereferences(0xc0005c2c80, 0xc0000a7708, 0x1d)
        /home/amr/Documents/misc/golang/cx/cx/fix_mem2.go:51 +0x3c5
github.com/skycoin/cx/cx.GetFinalOffset(0x1d, 0xc0005c2c80, 0x1d)
        /home/amr/Documents/misc/golang/cx/cx/fix_mem3.go:37 +0x6f
github.com/skycoin/cx/cx.opIdentity(0xc000168c60, 0x1d)
        /home/amr/Documents/misc/golang/cx/cx/op_misc.go:24 +0x8c
github.com/skycoin/cx/cx.(*CXCall).ccall(0xc00024c018, 0xc00015a0e0, 0x0, 0x0)
        /home/amr/Documents/misc/golang/cx/cx/execute.go:323 +0x5a9
github.com/skycoin/cx/cx.(*CXProgram).Run(0xc00015a0e0, 0xa11501, 0xc0000a7bd0, 0xffffffffffffffff, 0x0, 0x0)
        /home/amr/Documents/misc/golang/cx/cx/execute.go:119 +0x2f1
github.com/skycoin/cx/cx.(*CXProgram).RunCompiled(0xc00015a0e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa45fc0)
        /home/amr/Documents/misc/golang/cx/cx/execute.go:238 +0x2ff
main.runProgram(0x0, 0xab7c88, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/amr/Documents/misc/golang/cx/cmd/cx/main.go:204 +0x11a
main.Run(0xc000020050, 0x1, 0x1)
        /home/amr/Documents/misc/golang/cx/cmd/cx/main.go:92 +0x48e
main.main()
        /home/amr/Documents/misc/golang/cx/cmd/cx/main.go:24 +0x66```

**Comment by Diablo2050** [comment]
And the last script ackermann-function.cx generates the following error:
 ```error: ackermann-function.cx:8 function 'i32.bool' does not exist
panic: runtime error: index out of range [-1]

goroutine 1 [running, locked to thread]:
github.com/skycoin/cx/cxgo/actions.PostfixExpressionFunCall(0x0, 0x0, 0x0, 0xc0001da068, 0x1, 0x1, 0x0, 0x1, 0x0)
        /home/amr/Documents/misc/golang/cx/cxgo/actions/postfix.go:156 +0x26a
github.com/skycoin/cx/cxgo/parser.yyParse(0xac6488, 0xc0005b2090, 0xc0005b2090)
        /home/amr/Documents/misc/golang/cx/cxgo/parser/cxgo.go:2222 +0x7445
github.com/skycoin/cx/cxgo/parser.Parse(...)
        /home/amr/Documents/misc/golang/cx/cxgo/parser/cxgo.go:18
github.com/skycoin/cx/cxgo/cxgo.ParseSourceCode(0xc0001da498, 0x1, 0x1, 0xc0001bce50, 0x1, 0x1)
        /home/amr/Documents/misc/golang/cx/cxgo/cxgo/cxgo.go:78 +0x40f
main.parseProgram(0x0, 0xab7c88, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/amr/Documents/misc/golang/cx/cmd/cx/main.go:163 +0x348
main.Run(0xc0000cc010, 0x1, 0x1)
        /home/amr/Documents/misc/golang/cx/cmd/cx/main.go:91 +0x368
main.main()
        /home/amr/Documents/misc/golang/cx/cmd/cx/main.go:24 +0x66```
