### ISSUE TITLE
Panic when variable used in if statement without parenthesis.

### ISSUE THREAD

**Issue by asahi3g** [skycoin/cx#56]
```
package main
func main ()() {
    var t i32 = 3
    var TEST i32 = 3

    if t == 3 {
    }
    if t == TEST { // if (t == TEST) doesn't panic
        //printf("TEST %d\n", TEST)
    }
}
```
output 1:
```
test_56.cx:11: syntax error: unexpected SEMICOLON
panic: type 'TEST' does not exist

goroutine 1 [running, locked to thread]:
github.com/skycoin/cx/cxgo/actions.PrimaryStructLiteral(0xc420345090, 0x4, 0x0, 0x0, 0x0, 0x3, 0x4, 0x3)
	/home/reash/go/src/github.com/skycoin/cx/cxgo/actions/cxgo_compiled.go:671 +0x733
main.yyParse(0x952a40, 0xc420076140, 0xc420076140)
	/home/reash/go/src/github.com/skycoin/cx/cxgo/cxgo.go:1997 +0x4f37
main.main()
	/home/reash/go/src/github.com/skycoin/cx/cxgo/cxgo.nn.go:8550 +0x1509
```
output 2: when uncommenting the printf line.
```
test_56.cx:10: syntax error: unexpected LPAREN
```

**Comment by asahi3g** [comment]
Fixed.
