### ISSUE TITLE
Left hand side of , is not compiled

### ISSUE THREAD

**Issue by vidya88** [skycoin/cx#62]
@asahi3g commented on Mar 12

**To Reproduce**
```
package main
func fooA() {
	printf("fooA\n")
}
func fooB()() {
	printf("fooB\n")
}
func main()() {
	var i i32
	fooA(&i), 
	fooB()
	panic(true, false, "must not compile")
}
```
**Expected behavior**
Compilation error

**Screenshots**
```
fooB
byts1 [1]
byts2 [0]
tests/pending_13.cx: 16: result was not equal to the expected value; must not compile
tests/pending_13.cx : 16, must not compile
error: tests/pending_13.cx:16, CX_ASSERT, 4
```
**Desktop:**

- OS: Linux
- CX Version : 0.6.1, d8775bf

**Comment by vidya88** [comment]
@ingwal commented on Mar 12

This is also wrong in another way: You shouldn't be able to call fooA() with a non-empty parameter list

**Comment by archerixx** [comment]
Removing `,` from `fooA(&i),` produces error, but leaving as is, doesn't call `fooA()`, but doesnt produce error

Error:
```
error: test1.cx:3, CX_RUNTIME_ERROR, runtime error: index out of range [0] with length 0
===Callstack===
>>> fooA()
>>> main()
Expressions
        test1.cx:10 : fooA() : 0

goroutine 1 [running, locked to thread]:
runtime/debug.Stack(0x58, 0x0, 0x0)
        C:/Program Files/Go/src/runtime/debug/stack.go:24 +0xa5
runtime/debug.PrintStack()
        C:/Program Files/Go/src/runtime/debug/stack.go:16 +0x29
github.com/skycoin/cx/cx.runtimeErrorInfo(0x7ff7fc3b80c0, 0xc000098048, 0xc000098001, 0x5)
        C:/Users/tursi/OneDrive/Desktop/go-workspace/src/github.com/skycoin/CX/cx/utilities.go:882 +0x2dd
github.com/skycoin/cx/cx.RuntimeError()
        C:/Users/tursi/OneDrive/Desktop/go-workspace/src/github.com/skycoin/CX/cx/utilities.go:905 +0x185
panic(0x7ff7fc3b80c0, 0xc000098048)
        C:/Program Files/Go/src/runtime/panic.go:965 +0x1c7
github.com/skycoin/cx/cx.(*CXCall).ccall(0xc000166000, 0xc00021a0e0, 0x0, 0x0)
        C:/Users/tursi/OneDrive/Desktop/go-workspace/src/github.com/skycoin/CX/cx/execute.go:535 +0x17df
github.com/skycoin/cx/cx.(*CXProgram).Run(0xc00021a0e0, 0x7ff7fc3e7701, 0xc00017bbd0, 0xffffffffffffffff, 0x0, 0x0)
        C:/Users/tursi/OneDrive/Desktop/go-workspace/src/github.com/skycoin/CX/cx/execute.go:119 +0x2f2
github.com/skycoin/cx/cx.(*CXProgram).RunCompiled(0xc00021a0e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7ff7fc41f098)
        C:/Users/tursi/OneDrive/Desktop/go-workspace/src/github.com/skycoin/CX/cx/execute.go:238 +0x31f
main.runProgram(0x0, 0x7ff7fc49f248, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        C:/Users/tursi/OneDrive/Desktop/go-workspace/src/github.com/skycoin/CX/cmd/cx/main.go:222 +0x125
main.Run(0xc0000503d0, 0x1, 0x1)
        C:/Users/tursi/OneDrive/Desktop/go-workspace/src/github.com/skycoin/CX/cmd/cx/main.go:110 +0x528
main.main()
        C:/Users/tursi/OneDrive/Desktop/go-workspace/src/github.com/skycoin/CX/cmd/cx/main.go:24 +0x6f
```
