### ISSUE TITLE
`make build` fails when using 0.8.0 source archive

### ISSUE THREAD

**Issue by 0pcom** [skycoin/cx#728]
updating the AUR package for CX to the latest version ; the build fails for me like this

```
package github.com/skycoin/cx/cmd/cx
	imports github.com/skycoin/cx/cxfx
	imports github.com/skycoin/cx/cx/base: build constraints exclude all Go files in /home/user/.cache/AUR/cx/src/go/src/github.com/skycoin/cx/cx/base

```

while `make build` hangs indefinitely instead of producing an error

**Comment by kenje4090** [comment]
Hello @0pcom , may I ask for more details about this? You ran `make build` for this cx repo and you got that result?

**Comment by 0pcom** [comment]
ok the issue with the AUR package may have been a wrong path / artifact from when the github organization was SkycoinProject. I noticed that afterwards and forgot to update this issue.

I was able to compile cx from the source archive here but when I try to execute it I get the error:

```
[user@host cx-0.8.0]$ bin/cx help
flag "--min-heap-free" begins with -
panic: flag "--min-heap-free" begins with -

goroutine 1 [running, locked to thread]:
flag.(*FlagSet).Var(0xc000078540, {0xa196e8, 0xc000126550}, {0x96356e, 0x2}, {0x989ae2, 0x15})
	/usr/lib/go/src/flag/flag.go:864 +0x439
flag.(*FlagSet).Float64Var(...)
	/usr/lib/go/src/flag/flag.go:788
main.parseFlags(0xc000126500, {0xc000020050, 0x455487, 0x1})
	/home/user/go/src/github.com/skycoin/cx-0.8.0/cmd/cx/flags.go:80 +0x3ae
main.Run({0xc000020050, 0x1, 0x1})
	/home/user/go/src/github.com/skycoin/cx-0.8.0/cmd/cx/main.go:33 +0xf8
main.main()
	/home/user/go/src/github.com/skycoin/cx-0.8.0/cmd/cx/main.go:24 +0x45

```
