### ISSUE TITLE
empty code blocks (even if they contain commented-out lines) crash like this:

### ISSUE THREAD

**Issue by corpusc** [skycoin/cx#82]
panic: runtime error: index out of range

goroutine 1 [running, locked to thread]:
github.com/skycoin/cx/cx.(*CXCall).ccall(0xc00015e050, 0xc0000e20c0, 0x0, 0x0)
        C:/OneDrive/Programming/Code/WORK/GoApps/src/github.com/skycoin/cx/cx/execute.go:216 +0x540
github.com/skycoin/cx/cx.(*CXProgram).RunCompiled(0xc0000e20c0, 0x0, 0x4, 0xc00012adc0)
        C:/OneDrive/Programming/Code/WORK/GoApps/src/github.com/skycoin/cx/cx/execute.go:171 +0x26f
main.main()
        C:/OneDrive/Programming/Code/WORK/GoApps/src/github.com/skycoin/cx/cxgo/cxgo.nn.go:8619 +0xd61

**Comment by corpusc** [comment]
this seems to be fixed.  i've had at least 3 different empty code blocks in my code recently, which caused no problem.  

i'm not gonna close this tho, since i believe (according to fairly recent new practices), CX is now adding tests for anything that was once filed under "Issues"
